name: setup

description: Setup Node, cache and install deps

inputs:
  node_version:
    description: Node Version
    required: false
    default: '16'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2.2.4

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'pnpm'
        registry-url: https://registry.npmjs.org/

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Install NPM Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v3
