name: Test

description: Lint, Build and Test
inputs:
  CODACY_PROJECT_TOKEN:
    required: true

runs:
  using: composite

  steps:
    - name: Lint
      shell: bash
      run: pnpx nx affected:lint --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD  }}

    - name: Build
      shell: bash
      run: pnpx nx affected:build --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD  }}

    - name: Test
      shell: bash
      run: npx nx affected --target=test --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD  }}

    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ inputs.CODACY_PROJECT_TOKEN }}
        coverage-reports: ./coverage/packages/qwik-router/lcov.info

    # - name: E2E Tests
    #   shell: bash
    #   run: npx nx affected --target=e2e --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD  }}
