name: Release

on:
  workflow_dispatch:
    inputs:
      type:
        required: true
        type: choice
        description: Release type
        options:
          - patch
          - minor
          - major
        default: 'patch'
      package:
        required: true
        type: choice
        description: Package to release
        options:
          - qwik-router

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup

      - name: Check
        uses: ./.github/actions/check

  release:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpx nx run ${{ inputs.package }}:version --releaseAs=${{ inputs.type }} --push=true --baseBranch=${{ github.ref_name }}
